name: github-release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  github-release:
    name: Publish github release
    if: github.repository == 'skyclouds2001/storage-buckets-polyfill'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: softprops/action-gh-release@v2.1.0
        with:
          body: |
            Please refer to [README.md](https://github.com/skyclouds2001/storage-buckets-polyfill/blob/master/README.md) for details.
