name: npm-release

on:
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write

jobs:
  npm-release:
    name: Publish npm release
    if: github.repository == 'skyclouds2001/storage-buckets-polyfill'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Publish package to npm
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
